module.exports = {
    SWITCH_BACKUP_POWER: "SWITCH_BACKUP_POWER",
    ENTER_SAFE_MODE: "ENTER_SAFE_MODE",
    RESTART_SENSOR: "RESTART_SENSOR",
    CALIBRATE_THRUSTER: "CALIBRATE_THRUSTER",
    RESET_COMMUNICATION: "RESET_COMMUNICATION"
};